name: Proto Buf Publishing - Action
# Protobuf runs buf (https://buf.build/) push updated proto files to https://buf.build/cosmwasm/wasmd
# This workflow is only run when a .proto file has been changed
on:
  push:
    branches:
      - main
      - starname11
    paths:
      - 'proto/**'

    # Sequence of patterns matched against refs/tags
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+.*" # Push events to matching v*, //i.e. v20.15.10, v0.27.0-rc1

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build container
        uses: docker/build-push-action@v1
        with:
          username: iov-one
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: https://ghcr.io
          repository: iov-one/starnamed
          tag_with_sha: true